(global-set-key (kbd "C-h") 'delete-backward-char)
(setq visible-bell t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(setq inhibit-startup-message t)
(electric-pair-mode 1)
(show-paren-mode 1)
(setq make-backup-files nil)
(setq auto-save-default nil)
(font-spec :family "Migu 1M" :size 14)
