
#[shell]
#program = "c:\\Windows\\System32\\wsl.exe ~ -d Ubuntu-24.04"

#[bell]
#duration = 10
#color = "#333333"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0
smooth_motion = true
smooth_motion_factor = 0.7
smooth_motion_spring = 0.7
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0
# block_replace_shape = "underline"

[font]
normal = { family = "Migu 1M", style = "Regular" }
offset = { x = 1, y = 2 }
size = 14

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
dimensions = { columns = 180, lines = 48 }
decorations = "None"
padding = { x = 4, y = 4 }
opacity = 0.8

[general]
import = [
  "tokyonight_night.toml"
]
